name: TODO API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Docker Compose
        run: |
          # Check if docker compose works
          if ! docker compose version >/dev/null 2>&1; then
            echo "Installing traditional docker-compose..."
            sudo apt-get update
            sudo apt-get install -y docker-compose
            # Create compose plugin simulation
            sudo mkdir -p /usr/local/lib/docker/cli-plugins
            sudo ln -sf /usr/bin/docker-compose /usr/local/lib/docker/cli-plugins/docker-compose
          fi
          # Verify it works
          docker compose version || docker-compose version

      - name: Run tests
        run: |
          chmod +x run-tests.sh
          ./run-tests.sh
